# Variable 'artifactName' was defined in the Variables tab - This is from my fix branch
# Agent Queue 'Azure Pipelines' was used with unrecognized Agent Specification, vmImage property must be specified to determine image - https://docs.microsoft.com/en-us/azure/devops/pipelines/agents/hosted?view=azure-devops&tabs=yaml#software
variables:
  - name: 'BuildParameters.configuration'
    value: release
  - name: 'isMain'
    value: $[eq(variables['Build.SourceBranch'], 'refs/heads/main')]
  # - name: 'intentSolutionPath'
  #   value: 'intent'
  # - group: 'Intent Architect Credentials'

pr:
  branches:
    include:
      - main
  paths:
    include:
    - adminportal
trigger:
  branches:
    include:
      - main
  paths:
    include:
    - adminportal

pool:
  name: Azure Pipelines

stages:
  - stage: build
    jobs:  
      - job: Job_1
        displayName: Build_Shesha_AdminPortal_And_Modules
        pool:
          vmImage: windows-latest
        steps:
          - task: PowerShell@2
            displayName: Check if Pull Request
            inputs:
              targetType: 'inline'
              script: |
                $targetBranch = ""
                if ("$(Build.SourceBranch)" -like "*/pull/*")
                {
                    $targetBranch = "$(System.PullRequest.TargetBranch)"
                    write-host "This is a Pull Request and the target branch is: $targetBranch"
                    write-host "##vso[task.setvariable variable=prTargetBranch]$targetBranch"
                }
                write-host "This is not a Pull Request and the target branch is set to empty string"
                write-host "##vso[task.setvariable variable=prTargetBranch]''"
              workingDirectory: '$(System.DefaultWorkingDirectory)'
          - task: PowerShell@2
            displayName: Check to establish if this pipeline was triggered from a tag
            inputs:
              filePath: 'ReleaseFlow.ps1'
              workingDirectory: '$(System.DefaultWorkingDirectory)'
              arguments: '-PipeBuildNumber "$(Build.BuildNumber)" -PipeSourceBranch "$(Build.SourceBranch)" -PipeSourceVersion "$(Build.SourceVersion)" -PipeTargetBranch "$(prTargetBranch)" -PipeBuildId "$(Build.BuildId)"'
          - task: PowerShell@2
            displayName: Output to console the current branch and version
            inputs:
              targetType: 'inline'
              script: |
                write-host "The current branch is: $(currentBranch)"
                write-host "The current version is: $(versionNo)"
              workingDirectory: '$(System.DefaultWorkingDirectory)'
          - task: PowerShell@2
            displayName: Create a txt file to carry the original branch name to the release pipeline
            inputs:
              targetType: 'inline'
              script: |
                $variable = '$(currentBranch)'
                $variable | Out-File $(Build.ArtifactStagingDirectory)\branchName.txt
                Get-Content $(Build.ArtifactStagingDirectory)\branchName.txt
          - task: PublishBuildArtifacts@1
            displayName: 'Publish Artifact: api-info-1'
            inputs:
              PathtoPublish: '$(Build.ArtifactStagingDirectory)'
              ArtifactName: 'api-info-1'
          - task: NodeTool@0
            displayName: 'Use Node 20.11.0'
            retryCountOnTaskFailure: 3
            inputs:
              versionSpec: 20.11.0
          - task: Npm@1
            displayName: 'Npm Update Version'
            inputs:
              command: custom
              workingDir: adminportal
              verbose: false
              customCommand: 'version $(versionNo) --allow-same-version'
          - task: npmAuthenticate@0
            inputs:
              workingFile: 'adminportal/.npmrc'
          - task: PowerShell@2
            displayName: Version Module and NPM Install, Build and Publish
            inputs:
              targetType: 'inline'
              script: |
                $PSVersionTable

                write-host "The current branch is: $(currentBranch)"
                write-host "The current version is: $(versionNo)"

                # get the list of directories under packages
                $directories = Get-ChildItem -Path ./packages -Directory

                # iterate over each directory
                foreach ($directory in $directories) {
                    Write-Host "Start of Module Processing: $($directory.Name)"

                    Set-Location -Path $directory.FullName

                    Write-Host "Set Module Version"       
                    # npm version $(versionNo) --allow-same-version --no-git-tag-version

                    $filePath = "package.json"                    
                    $Jsonfile = Get-Content $filePath -raw | ConvertFrom-Json
                    $Jsonfile.name = "@shesha-io/$(Build.Repository.Name)"
                    $Jsonfile.version = "$(versionNo)"
                    ConvertTo-Json $Jsonfile -Depth 5 | Set-Content $filePath

                    # output the contents of the updated file
                    Get-Content $filePath

                    Write-Host "End of Module Configuration File Output: $($directory.Name)"
                }

                # Write-Host "Go back to AdminPortal Folder"       
                Set-Location -Path $(System.DefaultWorkingDirectory)/adminportal                

                # Write-Host "Set AdminPortal Version"       
                # npm version $(versionNo) --allow-same-version --no-git-tag-version                       

                # npm steps on root adminportal
                Write-Host "Install dependencies"
                npm install --legacy-peer-deps

                Write-Host "Build project"       
                npm run build

                if ("$(currentBranch)" -like "*/main"){
                    Write-Host "Publish library"
                    npm publish --workspace=*
                }

              workingDirectory: 'adminportal'
          - task: ArchiveFiles@2
            inputs:
              rootFolderOrFile: 'adminportal'
              includeRootFolder: false
              archiveType: 'zip'
              archiveFile: '$(Build.ArtifactStagingDirectory)/adminportal.zip'
              replaceExistingArchive: true
          - task: PublishBuildArtifacts@1
            displayName: 'Publish Artifact: shesha-adminportal'
            inputs:
              ArtifactName: adminportal              
